<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Statevia.Service.Runtime.Scheduler</RootNamespace>
    <AssemblyName>Statevia.Service.Runtime.Scheduler</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <ProjectReference Include="../../api/Statevia.Service.Api/Statevia.Service.Api.csproj" />
    <ProjectReference Include="../Statevia.Runtime/Statevia.Runtime.csproj" />
  </ItemGroup>
</Project>
