<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Statevia.Tools.Capacity</RootNamespace>
    <AssemblyName>Statevia.Tools.Capacity</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1303;CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Statevia.Tools.Capacity.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Definitions\*.yaml" />
  </ItemGroup>

</Project>
